# Generated by Django 2.1 on 2018-09-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_mark', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avi_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Predicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_mark', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avi_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=20)),
                ('student_password', models.CharField(max_length=20)),
                ('student_current_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='predicted',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avi_app.Student'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avi_app.Student'),
        ),
    ]
