# Generated by Django 2.1 on 2018-09-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_current_level',
            field=models.CharField(choices=[('select level', 'SELECT LEVEL'), ('yos1', 'YOS1'), ('yos2', 'YOS2'), ('yos3', 'YOS3'), ('honours', 'HONOURS'), ('masters', 'MASTERS')], default='select level', max_length=20),
        ),
    ]
