# Generated by Django 2.1 on 2018-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi_app', '0002_auto_20180930_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
